server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ["__meta_docker_container_id"]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: container
        replacement: "$1"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: service
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_project"]
        target_label: compose_project
      - target_label: job
        replacement: docker
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        regex: nginx
        target_label: job
        replacement: nginx
    pipeline_stages:
      - docker: {}

  - job_name: nginx-host-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
    relabel_configs:
      - source_labels: ["__path__"]
        regex: '.*/(access|error)\.log'
        target_label: log_type
